### ISSUE TITLE
Docs timely version does not work with the examples

### ISSUE THREAD

**Issue by bderooms** [TimelyDataflow/differential-dataflow#118]
Since we had to complain when doc examples were not working.

[dependencies]
timely = "0.5"
differential-dataflow = "0.5"

If you use these dependencies you get no function or associated item named `new` found for type `differential_dataflow::input::InputSession<_, _, _>` in the current scope

If I upgrade the dependencies according to what I see in the repository, I get other errors.

**Comment by sscdotopen** [comment]
Ran into the same issue a minute ago.

**Comment by frankmcsherry** [comment]
I'm sorry for being thick, but can you explain what is not working? Like, what you type and what does not work?

**Comment by sscdotopen** [comment]
The problem is that InputSession::new() does not exist in differential-dataflow 0.5.

**Comment by sscdotopen** [comment]
I realized that the link to the actual code was missing in this issue :) 

The example in https://github.com/frankmcsherry/differential-dataflow/blob/master/mdbook/src/chapter_0/chapter_0_1.md uses `InputSession::new` but https://github.com/frankmcsherry/differential-dataflow/blob/master/mdbook/src/chapter_0/chapter_0_0.md asks users to setup a project with differential-dataflow 0.5 which does not have this function. That's why the example does not compile.

**Comment by frankmcsherry** [comment]
Gotcha! Thanks; will fix ASAP! :D

**Comment by frankmcsherry** [comment]
Tada: https://github.com/frankmcsherry/differential-dataflow/commit/2b42748528d72820e3439a408922591dbebb96b4

**Comment by bderooms** [comment]
Great response and fix time guys!
