### ISSUE TITLE
How does a differential operator work really?

### ISSUE THREAD

**Issue by yilongli** [TimelyDataflow/differential-dataflow#128]
Hi Frank,

I have been trying to understand how the general implementation of differential operators works. I have tried to work through the CIDR'13 paper and your post (https://github.com/frankmcsherry/blog/blob/master/posts/2015-11-27.md). So far, the post seems more accessible to me so I will ask questions based on the post for now. 

Basically, I am getting stuck at the "Operator implementations" section. The second paragraph says:
```
Imagine we keep all received input differences and produced output differences, partitioned up by their associated key. We can reconstruct the input and output associated with a given key at any t, subtract from the output the operator logic applied to the input, and produce that as output for t.
```
I am not sure I understand what it means. Is it saying that the dumbest way to obtain `d_output_(1,1)` is to compute `distinct(d_input_(0,0) + d_input_(1,0) + d_input_(0,1) + d_input_(1,1)) - (d_output(0,0) + d_output(1,0) + d_output(0,1))`?

The following paragraph then starts with:
```
Ideally, we only need to pay attention to a restricted set of (key, t).
```
I think this is the first time you use the notation `(key, t)`. Since I don't see a clear definition I have to guess it's just another representation of `d_input_(x,y)`. For example, `d_input_(0,1) = { (dog, -1), (goat, 1) }` corresponds to `(dog, (0,1)) and (goat, (0,1))`. Am I right?

At this point, I assume we are going to talk about finding a better way to compute `d_output_(1,1)` which doesn't have to touch the potentially very large `...` in `d_input_(0,0)`. Unfortunately, I got completely lost in the following "Interesting times" section. I am unable to connect the example described in this section (i.e., `cat` gets incremented at both `(0,3)` and `(1,2)`) back to what we have set up so far. Fast forwarding to the end of this section, I see:
```
As it turns out, it is sufficient to compare the input and output for (key, t) pairs where t is the least upper bound of some subset of times at which the input associated with key changed.
```

I couldn't grasp this sentence either. Ideally, I think it would really help if there is a concrete example on how to compute `d_output_(1,1)` and `d_output(1,3)` given the following input differences (adapted from the `distinct` example used in the previous section):
```
(cat, +1, (0,0))
(dog, +1, (0,0))
...
(cat, +1, (1,0))
(dog, -1, (0,1))
(goat, +1, (0,1))
(cat, +1, (0,3))
(cat, +1, (1,2))
```

I tried to read the pseudocode to understand how it works but the code snippet doesn't seem to be self-contained. For example, I don't see the `SendBy`, `OnRecv`, `NotifyAt`, and `OnNotify` methods described in the Naiad paper and I don't know which variable is per-vertex state. I understand that it's a different implementation but I think a language-independent version of pseudocode written using the Naiad API would be really helpful for people coming from the Naiad paper.

Sorry for so many questions. Timely & differential dataflow are very exciting work and I hope to truly understand how it works. Thank you!

**Comment by frankmcsherry** [comment]
Thanks for the input. I'll try and write something up, but I have so far not gone and edited any existing blog posts (other than for typos or errors). So it would probably need to be new text that gets written. For what it is worth, you are 100% asking about the most complicated part of differential dataflow, the `distinct` operator (or `group` generally). Other parts get easier. :)

For your questions,

1. The first quoted region is just how you interpreted it. You *could* just re-materialize the input, apply the logic, and subtract the existing materialized output (all diffs less than the time in question).

2. The next quoted region is observing that it would be very expensive to do this, and ideally we would look at a subset of keys and times, rather than all keys and times. For example, if we see "camel" in the first round and it never changes, we shouldn't continue to re-assemble and re-evaluate the `distinct` logic for "camel".

3. The third quoted region is one rule for which pairs of key and time need to be reconsidered. Informally, it says that the very primitive logic

```rust
    for key in all_keys {
        for time in all_times {
            let input = reform_input(key, time);
            let output = reform_output(key, time);
            produce_output_changes(logic(input) - output);
        }
    }
```

could be replaced by

```rust
    for key in all_keys {
        for time in least_upper_bound(power_set(times_for(key))) {
            let input = reform_input(key, time);
            let output = reform_output(key, time);
            produce_output_changes(logic(input) - output);
        }
    }
```

meaning that for each key, we only need to re-evaluate the logic at times that are the least upper bound (in the lattice sense) of a subset of times for which the key experienced a change. This is also sketched in section 3.4 of the CIDR paper, and proven somewhere (possibly in [our FOSSACS paper](https://users.soe.ucsc.edu/~abadi/Papers/differential_revision-app.pdf), though I'm having a hard time finding the line; Gordon did prove it at one point though).

Algorithm 1 in the CIDR paper is *probably* the language agnostic version you are looking for. Derek implemented it directly in Python and was surprised to find that it worked as written.

**Comment by frankmcsherry** [comment]
I'm sorry to have lost track of this. Here are some answers:

1. Algorithm 1 is more general, in that it accepts arbitrary changes at arbitrary times. The Rust code only processes changes that it can determine are final. This mean the Rust code misses some opportunity to do speculative computation, but we also found (in Naiad) that speculative computation wasn't as helpful as you might think (we got our selves in trouble more often than we got out of trouble).

2. This re-use exists in the Rust code too, and is essential to differential dataflow. It corresponds to the partial order of timestamps, where the partial order allows us to use different subsets of updates when performing incremental computation.
