### ISSUE TITLE
Optimizing `.distinct_total().arrange_by_self()`

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#131]
I have a collection `Collection<_,V,_>` in the _root_ scope. I would like to apply `distinct_total()` to it and arrange the result by self, so I get `Arranged<_,V,(),_,_>` in the end (which I will then pass to `antijoin_arranged` from #130). The straightforward way:

```
collection.distinct_total().arrange_by_self()
```

creates two arrangements of the original collection: one inside `distinct_total` and one in `arrange_by_self()`. I wonder if there is a more memory-efficient solution that would, e.g., arrange and distinct the collection at the same time. Again, I only need this in the root scope.

Thanks!

**Comment by frankmcsherry** [comment]
There is not, to the best of my knowledge, a simpler way to do this. You can also crack open `group` and do a `distinct` where you get out the result arrangement. It should be about the same memory requirements as your approach above, but with different compute requirements (your example does some redundant work, but is also simpler because of the `_total`).

Depending on what you need the arrangement for, there could be a simpler implementation of the operators that *use* the collection, so that they could consume an arrangement containing all frequencies and do the distinct in their own logic. I'm just speculating there, though.

I suspect that what we should actually do is sit down together at some point, possibly as a result of one or both of us getting on airplanes, and do a bit of a deep dive into your codebase and attempting to go for (relatively) easy targets. If you are quite close to meeting the memory requirements of your users (vs them always wanting another 2x reduction) I suspect we could find some things to trim.

**Comment by ryzhyk** [comment]
Thanks, and fair enough.

`collection.distinct_total().arrange_by_self()` is not that bad actually, as I try to avoid `distinct_total` when possible by using simple static analysis to identify collections that are already distinct. Plus I reuse the resulting arrangements across multiple join and semijoin operators.
