### ISSUE TITLE
Q: In practice, should we just use tuples?

### ISSUE THREAD

**Issue by dhalperi** [TimelyDataflow/differential-dataflow#159]
I'm still more struggling with Rust than differential dataflow, but I'm having trouble getting off the ground in the hour-or-so I get to spend at a time.

Some preliminary issues:

* I'm having a hard time matching impedance between the Internet's opinion on Rust and TD code. E.g., "never use unwrap, use `Result/Box<Error>` instead" vs .. panic a lot. I'm just plodding along assuming whatever I choose to do is right.

* I didn't look hard, but I didn't see anything in `examples/` that uses input data from a file. So I did what is almost certainly stupid: copied some example off the internet that used `csv` and `serde` with structs to get my data into a sensible collection in few lines of code.

    This seemed like a good idea - structs are basically named tuples, and names are useful, right? But then first, it seemed unnecessarily slow both to execute and now to compile (1 line change to 50-line program takes 17s to recompile just the main program?). But again, the Internet suggests this may be par for the course with Rust.

Real Q:

I eventually got my data in and sorted by timestamp, but then I'm having a heck of a time getting DD to accept my structs. Need to implement the standard traits like Eq and Ord (okay, that's a good learning exercise) but now I've got to implement non-standard traits like Abomonation. @frankmcsherry did a pretty good job of making it clear in that Readme that I don't want to go any further.

Q: In practice, should I just use tuples and drop the named structs and everything else? Is there a better example I should see? Is there a better forum for these types of discussions?

**Comment by frankmcsherry** [comment]
Quick feedbacks (on vacay!):

1. I wouldn't worry too much about the internet's opinion on Rust philosophy. They are often wrong.
2. I usually re-copy/paste my code from [graph-map/parse](https://github.com/frankmcsherry/graph-map/blob/master/src/bin/parse.rs). There is also some "probably idiomatic" code in [tpchlike/types.rs](https://github.com/TimelyDataflow/differential-dataflow/blob/master/tpchlike/src/types.rs) where each type has a `From<&str>` implementation.

Using tuples is probably the easiest way to go. If you aren't familiar with `#[derive(Eq, Ord, ...)]` you'll want to use that (rather than "implement" the traits), at least assuming you want default implementations and just want to get to work. The traits are needed to do things like determine if two updates are to a common record, and should be coalesced/cancelled; it seems like something you'll need to provide somewhere. If `Abomonation` ends up being problematic, there is also a `bincode` flag you can use to switch the serialization over to serde-based traits.

This is a fine place to ask questions; you may also get a response in the [timely gitter channel](https://gitter.im/timely-dataflow/Lobby) but it has been a bit quiet of late.

**Comment by frankmcsherry** [comment]
Btw, you *should* be able to get structs up and working with an amount of code roughly proportional to (from timely's [logging.rs](https://github.com/TimelyDataflow/timely-dataflow/blob/master/src/logging.rs)):

```rust
#[derive(Serialize, Deserialize, Abomonation, Debug, Clone, Hash, Eq, PartialEq, Ord, PartialOrd)]
/// The creation of an `Operate` implementor.
pub struct OperatesEvent {
    /// Worker-unique identifier for the operator.
    pub id: usize,
    /// Sequence of nested scope identifiers indicating the path from the root to this instance.
    pub addr: Vec<usize>,
    /// A helpful name.
    pub name: String,
}
```

To use these derive statements, you'll need your `Cargo.toml` to contain things like

```
[dependencies]
serde = "1.0"
serde_derive = "1.0"
abomonation = "0.7"
abomonation_derive = "0.3"
```

And then your `main.rs` or `lib.rs` to have stuff like

```
#[macro_use]
extern crate abomonation_derive;
extern crate abomonation;
extern crate serde;
#[macro_use]
extern crate serde_derive;
```

That's a lot of guff, and you can probably pick/choose between `Serialize` and `Abomonation`, but once you have it in place it is not horribly painful (imo, but probably opinions vary. :)).

**Comment by dhalperi** [comment]
SGTM, definitely unblocked. Thanks!
