### ISSUE TITLE
`distinguish_since` or `advance_by` empty frontier clears trace

### ISSUE THREAD

**Issue by eoxxs** [TimelyDataflow/differential-dataflow#172]
I'm not sure if this is on us, but calling `distinguish_since` and `advance_by` with an empty frontier `&[]` on some trace and consequentially importing it in another dataflow does not produce any results.

It appears that here https://github.com/TimelyDataflow/differential-dataflow/blob/a8096d88b960eb5a4cbc7e961af8ef255e6b81cb/src/trace/implementations/spine_fueled.rs#L175-L179 `merging` and `pending` are cleared if the frontier is empty.

`through_frontier` and `advance_frontier` are also empty after a call to `advance_to` and `distinguish_by`.

`merging` and `pending` are used here: https://github.com/TimelyDataflow/differential-dataflow/blob/a8096d88b960eb5a4cbc7e961af8ef255e6b81cb/src/trace/implementations/spine_fueled.rs#L189-L198, which in turn is called in `new_listener` which dictates the batches and times in `import_core`.

That means that if we use this trace again we will not see any results.

**Comment by frankmcsherry** [comment]
I think I have given advice that one could call `distinguish_since(&[])` and all would be good, but this advice was bad (Niko and I ran into this). The problem is that it renders the trace "unusable" for joins against most other streams (it can still be used for other operators, just not join).

I hope I didn't give the advice to call `advance_by(&[])`, as this absolutely allows the trace to totally ignore this handle (informally: "all future query times will be in advance of something in `&[]`").

Ideally, one should call `advance_by(frontier)` and `distinguish_since(frontier)` as your frontiers move forward. Strictly speaking, `distinguish_since` is more horrible than this, and I'm optimistic that I can rewrite everything about it without having to tell anyone how the old version was supposed to work.

**Comment by eoxxs** [comment]
Oh forgot to close that one.

We'll be cautious and use an empty frontier :)
