### ISSUE TITLE
Possible memory leak in dogs^3

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#235]
This might be just another manifestation of #234, but submitting anyway in case it's not. Using the same dataflow graph, I insert a single graph edge and two nodes and then remove them at the next epoch in a loop. All is fine with one worker, but with `-w 3` I observe that the memory footprint of the program keep growing monotonically.  The repro is in the `dogs_leak` (no pun intended) branch of my DD fork:

https://github.com/ryzhyk/differential-dataflow/tree/dogs_leak

**Comment by frankmcsherry** [comment]
Just to start filling in data here. When I start this up it takes about 7MB; at 100,000 steps it has reached 10MB; at 200,000 steps it is at 16.6MB; at 300,000 steps it is at 16.9MB. Is this consistent with the growth that you were seeing?

It does seem to be a leak, but more subtle than I was imagining (phew!).

At 500,000 steps at it is at 17.0MB. I'm not certain I can distinguish this from the background operating system and allocator sorting out a working set. I'll put together some logging to see if the reported footprint is stable, and if not we'll need to use some other profiling tools to figure out if the persistent allocations are growing, or just the allocator working set.

**Comment by frankmcsherry** [comment]
At 1,000,000 steps it is at 17.6MB. I'll keep running it and see if it plateaus, or keeps growing.

**Comment by ryzhyk** [comment]
Interesting. I see much steeper growth, and it does not plateau.  Let me try to plot it.  What do you use to obtain those memory footprint numbers?

**Comment by frankmcsherry** [comment]
I'm just using Activity Monitor. I'm on a mac; perhaps the memory behavior is different here (the default allocator is not jemalloc, for example).

**Comment by ryzhyk** [comment]
Here is my exact command line (the number of workers being >1 is important):

```
cargo run --example validedges -- -w 3
```

Is this how you run it too?

I am on Linux and I see the memory footprint reported by `top` grow from 10 to 40MB at a roughly constant rate over a couple of minutes, and it keeps growing.

**Comment by ryzhyk** [comment]
Also, I just pushed the `dogs_leak` branch rebased on top of your fix to #234 just to be sure we run identical code.

**Comment by frankmcsherry** [comment]
I'm sorry, I read your notes badly and didn't observe the multiple workers requirement! I'm definitely seeing growth with that in place. I'll start pulling some numbers down. The communication mechanisms are different with multiple workers, which could be related. Await further information!

**Comment by frankmcsherry** [comment]
at 100 minutes of CPU time (78,000 steps) memory is at 281MB. It's growing for sure, but slowly.

**Comment by frankmcsherry** [comment]
At 100,000 steps memory is at 371MB.

**Comment by ryzhyk** [comment]
I've never run it till the end, but yep, seems consistent with what I see.

True, it does not leak super fast, but on the other hand this is basically an empty dataset.

**Comment by frankmcsherry** [comment]
Yup, sorry wasn't trying to argue that it was small, just taking notes. I don't yet know what part of the system is leaking; it could be the communication layer, it could be data storage, or some other random pile of buffers that are building up.

**Comment by frankmcsherry** [comment]
I think I've found the problem here. Or at least pretty clear symptoms. It is again the issue of large numbers of empty batches not being compacted. The problem as before was that the compaction was being driven by received batches, and because we still cannot transmit empty batches (timely dataflow requires a capability, and we do not have one) we never advance the physical merge frontier, and maintain long lists of empty batches.

I've made some modifications, and they may be incorrect so it's worth testing things again. Roughly, to my reading it is not important for the trace maintained by the `look_up` operator to prevent physical merging, and so the first thing it does is discard that capability. That removes all the logic that previously looked at incoming batches from the arrangement and advanced the physical merge frontier based on them (whose implementation was holding back merging). I don't see the reason that we need to prevent physical merging (i.e. why go slow, instead of allowing all merging all the times) but  it may turn out there was a good reason that we rediscover with testing. If so, there is logic to copy from the `join` and `reduce` logic (each of which want restricted cursors, and so want to prevent physical merging).

**Comment by frankmcsherry** [comment]
#244 should fix this, at least as best as I understand it. If you don't mind giving that a spin, I'd appreciate it! (for me, growth seems to be much less, but I can't say it is zero; however, the observed defect of growing numbers of empty batches seems to be gone).

**Comment by ryzhyk** [comment]
I think this did the trick!  I don't see any leaks or regressions. In addition, delta queries are running significantly faster now. It appears that all those uncompacted batches were slowing things down quite a bit!

Our test suite for dogs is currently fairly limited, so this is very far from exhaustive testing.  I will add more such tests in the next few days (in DDlog this is now a matter of annotating a rule with a special attribute to get it to compile into a delta query, so should not be too hard).

**Comment by ryzhyk** [comment]
Did some more testing, everything still looking good.
